name: Build and Push to ECR

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Login to ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Set Version
      run: echo "VERSION=v${{ github.run_number }}" >> $GITHUB_ENV

    - name: Build Image
      run: |
        docker build -t campfire-tomcat:$VERSION .

    - name: Tag Image
      run: |
        docker tag campfire-tomcat:$VERSION \
        303154344513.dkr.ecr.ap-south-1.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:$VERSION

        docker tag campfire-tomcat:$VERSION \
        303154344513.dkr.ecr.ap-south-1.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest

    - name: Push Image
      run: |
        docker push 303154344513.dkr.ecr.ap-south-1.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:$VERSION
        docker push 303154344513.dkr.ecr.ap-south-1.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest
